### ISSUE TITLE
Matrix outputs returned as 9-element vector?

### ISSUE THREAD

**Issue by crbinz** [JuliaAstro/ERFA.jl#20]
Maybe there's a good reason for this, but in functions like `eraPn06a`, which returns a few 3x3 rotation matrices, they're instead returned as 9-element vectors, which must be reshaped. Would it be better to just return them as a matrix, instead?

**Comment by nirinA** [comment]
the reason is that the arguments for ``ccall`` are initializes as ``zeros(9)``, so they are returned as 9-element array.
i agreed that as they are matrices, they might be represented as 3x3 matrices; if this need to be changed, i would change their initialization as ``zeros((3,3))`` instead of reshaping the results.
i don't care much about changing them unless there is some performance gain. i will check.

**Comment by nirinA** [comment]
you can find the changes in the initialization here:

https://github.com/nirinA/ERFA.jl/blob/matrices_as_3x3/src/ERFA.jl

this just changes ``zeros(9)`` to ``zeros((3,3))`` and likewise, ``zeros(6)`` to ``zeros((2,3))``; and should be more compliant with what the functions have to return

**Comment by crbinz** [comment]
@nirinA were you planning on doing a PR with this change?

**Comment by nirinA** [comment]
i planned to make the changes with a new release of liberfa; but there is no new version up to now (unless i missed it). so i think i'll first merge your PR in #23, then will work on this in the next few days.

**Comment by nirinA** [comment]
i pushed a new PR for those changes, and as far as i checked, they should be backward compatible. thank you for your patience.

**Comment by crbinz** [comment]
Great, thanks! No worries about the wait at all, I just didn't want this to be forgotten about.
